#!/usr/bin/env bash
#
# Generates the production signing key for this fork and writes signing.properties.
#
# Run this yourself: the password is read from your terminal, never passed as an
# argument (which would put it in the process list) and never stored anywhere
# except signing.properties, which is git-ignored and created mode 600.
#
# An Android release key cannot be rotated. Every future update must be signed
# with the same key or Android will refuse to install it over an existing copy.
# Back the keystore up somewhere durable before you ship anything with it.
#
# Usage:
#   scripts/generate-release-key.sh [keystore-path] [alias]

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYSTORE="${1:-$HOME/keys/cmfa-ai-release.keystore}"
ALIAS="${2:-cmfa-ai}"
PROPS="$REPO_ROOT/signing.properties"

die() { printf '\033[31merror:\033[0m %s\n' "$1" >&2; exit 1; }
note() { printf '\033[36m%s\033[0m\n' "$1"; }

# Resolve to an absolute path before comparing against the repo.
mkdir -p "$(dirname "$KEYSTORE")"
KEYSTORE="$(cd "$(dirname "$KEYSTORE")" && pwd)/$(basename "$KEYSTORE")"

# A key inside the working tree is one `git add -f` away from being published,
# which is exactly how the repository ended up with a public release.keystore.
case "$KEYSTORE" in
    "$REPO_ROOT"/*) die "refusing to create the key inside the repository: $KEYSTORE" ;;
esac

[ -e "$KEYSTORE" ] && die "already exists, refusing to overwrite: $KEYSTORE"

# macOS ships /usr/bin/keytool as a stub that exists but exits 1 with "Unable to
# locate a Java Runtime" when no JDK is selected, and Homebrew's JDKs are
# keg-only so /usr/libexec/java_home does not see them either. Every candidate is
# therefore probed by running it, not by testing for the file.
resolve_keytool() {
    local candidate
    for candidate in \
        "${JAVA_HOME:-}/bin/keytool" \
        "$(/usr/libexec/java_home 2>/dev/null || true)/bin/keytool" \
        /opt/homebrew/opt/openjdk/bin/keytool \
        /opt/homebrew/opt/openjdk@21/bin/keytool \
        /opt/homebrew/opt/openjdk@17/bin/keytool \
        /usr/local/opt/openjdk/bin/keytool \
        /usr/local/opt/openjdk@21/bin/keytool \
        /usr/local/opt/openjdk@17/bin/keytool \
        "$(command -v keytool 2>/dev/null || true)"
    do
        case "$candidate" in ""|"/bin/keytool") continue ;; esac
        [ -x "$candidate" ] || continue
        "$candidate" -help >/dev/null 2>&1 || continue
        printf '%s' "$candidate"
        return 0
    done
    return 1
}

KEYTOOL="$(resolve_keytool)" || die "no usable JDK found. Install one (brew install openjdk@21) or set JAVA_HOME."
note "keytool  : $KEYTOOL"

note "Keystore : $KEYSTORE"
note "Alias    : $ALIAS"
echo

read -rsp "Password for the new keystore (min 6 chars): " PW1; echo
read -rsp "Re-enter to confirm: " PW2; echo
[ "$PW1" = "$PW2" ] || die "passwords do not match"
[ "${#PW1}" -ge 6 ] || die "keytool requires at least 6 characters"
unset PW2

# Fed over stdin rather than -storepass so the password never appears in the
# process list. The trailing blank line answers "key password (RETURN if same
# as keystore password)", keeping both passwords identical.
printf '%s\n%s\n\n' "$PW1" "$PW1" | "$KEYTOOL" -genkeypair \
    -keystore "$KEYSTORE" \
    -alias "$ALIAS" \
    -keyalg RSA \
    -keysize 4096 \
    -validity 10000 \
    -dname "CN=$ALIAS, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown" \
    >/dev/null

chmod 600 "$KEYSTORE"

umask 077
cat > "$PROPS" <<PROPERTIES
# Generated by scripts/generate-release-key.sh. Git-ignored — never commit this.
keystore.path=$KEYSTORE
keystore.password=$PW1
key.alias=$ALIAS
key.password=$PW1
PROPERTIES
chmod 600 "$PROPS"

echo
note "Created $KEYSTORE"
note "Wrote   $PROPS  (mode 600, git-ignored)"
echo
echo "Certificate fingerprint — record this, it identifies your builds:"
printf '%s\n' "$PW1" | "$KEYTOOL" -list -v -keystore "$KEYSTORE" -alias "$ALIAS" \
    | grep -E "SHA256:" || true
unset PW1
echo
cat <<'REMINDER'
Next:
  1. Back up the keystore file AND its password somewhere durable and private.
     Lose either and you can never publish an update to an installed app again.
  2. Build:  ./gradlew :app:assembleAgentRelease -PagentArm64Only=true
REMINDER
